---
abstract: 'Multi host remote control over ssh'
author:
  - 'mst - Matt S. Trout (cpan:MSTROUT) <mst@shadowcat.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tak
no_index:
  directory:
    - t
    - inc
  file:
    - lib/Tak/STDIONode.pm
requires:
  Capture::Tiny: 0.11
  Config::Settings: 0.02
  Data::Dumper::Concise: 2.020
  Eval::WithLexicals: 1.001000
  IO::All: 0.44
  IPC::System::Simple: 1.21
  JSON::PP: 2.27104
  Log::Contextual: 0.004
  Moo: 0.009012
  Net::OpenSSH: 0.52
  warnings::illegalproto: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://git.shadowcat.co.uk/scpubgit/Tak.git
version: 0.001002
